---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-logging
  name: kibana
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
  - port: 80
    name: webinterface
    targetPort: 5601
  selector:
    app: kibana
---
